### ISSUE TITLE
[Solved] '"git add realwork.txt"' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by pythonl1** [benhutchins/greenhat.py#1]
I am getting this error when I try to run `greenhat.py` file in my local repo. `python greenhat.py (50)``. I am using``python3.4``

`nothing added to commit but untracked files present
'"git add realwork.txt"' is not recognized as an internal or external command,
operable program or batch file.
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
        greenhat.py
        realwork.txt`

**Comment by benhutchins** [comment]
I believe b018715ecede89186d79284fe1835b5b4a4a76b0 should resolve this. This issue is that Python 3 changed the way `subprocess.call` method slightly, the way it was written tried to run `git add realwork.txt` a single command. I've revised it so it should run `git` with arguments.

**Comment by benhutchins** [comment]
26c203844e9e8e03928fec9bedbe397b83cc34df should also add support for all of Python 3

**Comment by pythonl1** [comment]
Thank you very much! It worked. Please close this thread :)
